const GET_EXAMPLE_ERROR = 'example/GET_EXAMPLE_ERROR';
const GET_EXAMPLE_EMPTY = 'example/GET_EXAMPLE_EMPTY';
const GET_EXAMPLE_SUCCESS = 'example/GET_EXAMPLE_SUCCESS';
const GET_EXAMPLE_LOADING = 'example/GET_EXAMPLE_LOADING';

export {
  GET_EXAMPLE_ERROR,
  GET_EXAMPLE_EMPTY,
  GET_EXAMPLE_SUCCESS,
  GET_EXAMPLE_LOADING
};
