const GET_HEADER_MENU_ERROR = 'app/GET_HEADER_MENU_ERROR';
const GET_HEADER_MENU_SUCCESS = 'app/GET_HEADER_MENU_SUCCESS';
const GET_HEADER_MENU_EMPTY = 'app/GET_HEADER_MENU_EMPTY';

export {
  GET_HEADER_MENU_ERROR,
  GET_HEADER_MENU_SUCCESS,
  GET_HEADER_MENU_EMPTY
};
