const GET_HOME_ERROR = "home/GET_HOME_ERROR";
const GET_HOME_EMPTY = "home/GET_HOME_EMPTY";
const GET_HOME_SUCCESS = "home/GET_HOME_SUCCESS";

export { GET_HOME_ERROR, GET_HOME_EMPTY, GET_HOME_SUCCESS };
